### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by RBFraphael** [KazzKzpk/KrupaBOX#1]
Hi!

I'm from Brazil and I'm in a project that uses this framework, but I'm encountering some difficult to understand your code. Can you provide me documentation or something that can help on working with projects which uses your framework?

Thanks!

**Comment by KazzKzpk** [comment]
Documentation will be done when I am available.
Try to open the files in the System folder and understand the code.

Kind regards,
Kzpk.
